POST https://web-demo.online/admin/notify
content-type: application/json

{
    "listUser": ["61549170d86e7a2ba4af28ed", "615331ffc7dc43e2e5c84f45"],
    "content": "Hello"

}

###

POST https://localhost:3000/admin/notify_banner
content-type: application/json

{
    "content": "Hello"

}

###
PATCH http://localhost:3000/admin/product
Content-Type: application/json

{
    "idProduct": "611e71cf37725149c830aa05",
    "update": {
        "quantity": 10
    }
}

###
PATCH https://web-demo.online/admin/category
Content-Type: application/json

{
    "idCategory": "61129ba8516b371f383a1742",
    "update": {
        "products": [ 
            "611ca9d835f54f93292951c6"
        ],
        "name1": "demo1"
    }
}

###
POST https://web-demo.online/admin/category
Content-Type: application/json

{
    "id": "c5",
    "products": [ 
        "611ca9d835f54f93292951c6", 
        "61125d66516b371f38dc1b40"
        
    ],
    "name": "demo"
}

###
POST http://localhost:3000/admin/product
Content-Type: application/json

{
    "id" : "31",
    "img" : "https://cdn.shopify.com/s/files/1/2695/0984/products/materio-free-banner.png?v=1629437936",
    "title" : "demo",
    "rate" : "4.7",
    "price" : 0,
    "description" : "demo",
    "ventor" : "demo",
    "category" : "Free",
    "quantity" : 10,
    "category" : "FREE"
}

###
DELETE http://localhost:3000/admin/category
Content-Type: application/json

{
    "idCategory": "6160158b0435705dbe1464c7"
}

###
DELETE http://localhost:3000/admin/product
Content-Type: application/json

{
    "idProduct": "61601491e5599702fd7daf41"
}

###
PATCH http://localhost:3000/admin/user
Content-Type: application/json

{
    "idUser": "6151a7b8ac39ee8974e0d43a",
    "update": {
    "email" : "A van teo",
    "firstName" : "asfasfasfasfsa",
    "lastName" : "sdgsdgsdgsdgsdgsd",
    "status" : "Active",
    "gender" : "Male",
    "phonenumber" : "1572727",
    "role" : "User",
    "wishlist" : [],
    "cart" : ["dfsdfsdfd"],
    "DOB": "Mon Oct 11 2021 13:44:00 GMT+0700 (Indochina Time)"
    }
}

###
DELETE https://web-demo.online/admin/user
Content-Type: application/json

{
    "idUser": "6151a7b8ac39ee8974e0d43a"
}

###
DELETE https://web-demo.online/admin/order
Content-Type: application/json

{
    "idOrder": "615e693b93c2b1eaa5f52149"
}

###
POST http://localhost:3000/admin/discount
Content-Type: application/json

{
    "code": "HELLOWORLD",
    "expireDate": "Mon Oct 15 2021 13:44:00 GMT+0700 (Indochina Time)",
    "startDate": "Mon Oct 11 2021 13:44:00 GMT+0700 (Indochina Time)",
    "amount": 50

}

###
POST http://localhost:3000/checkDiscount
Content-Type: application/json

{
    "code": ""
}

###
POST http://localhost:3000/admin/user
Content-Type: application/json

{
    "email": "nhattan24121999@gmail.com",
    "password": "123456",
    "firstName": "Nhat",
    "lastName": "Tan",
    "gender": "Male",
    "DOB": "Tue Oct 12 2021 20:34:16 GMT+0700 (Indochina Time)",
    "phonenumber": "2348543241"
}

###
GET https://web-demo.online/admin/discount

###
PATCH http://localhost:3000/admin/discount  
Content-Type: application/json

{
    "code": "HELLOWORLD",
    "expireDate": "Tue Oct 12 2021 20:34:16 GMT+0700 (Indochina Time)",
    "amount": 60
}

###
