@host = http://localhost:3000
@host1 = https://web-demo.online

###
POST {{host}}/admin/notify
content-type: application/json

{
    "listUser": ["61549170d86e7a2ba4af28ed", "616590ce2cf0c93c3f9153ce"],
    "content": "Hello"

}

###

POST {{host}}/admin/notify_banner
content-type: application/json

{
    "content": "Hello"

}

###
PATCH {{host}}/admin/product
Content-Type: application/json

{
    "idProduct": "611e71cf37725149c830aa05",
    "update": {
        "quantity": 10
    }
}

###
PATCH {{host}}/admin/category
Content-Type: application/json

{
    "idCategory": "61129ba8516b371f383a1742",
    "update": {
        "products": [ 
            "611ca9d835f54f93292951c6"
        ],
        "name1": "demo1"
    }
}

###
POST {{host}}/admin/category
Content-Type: application/json

{
    "products": [ 
        "611ca9d835f54f93292951c6", 
        "61125d66516b371f38dc1b40"
        
    ],
    "name": "demo1"
}

###
POST {{host}}/admin/product
Content-Type: application/json

{
    "id" : "31",
    "img" : "https://cdn.shopify.com/s/files/1/2695/0984/products/materio-free-banner.png?v=1629437936",
    "title" : "demo",
    "rate" : "4.7",
    "price" : 0,
    "description" : "demo",
    "ventor" : "demo",
    "category" : "Free",
    "quantity" : 10,
    "category" : "FREE"
}

###
DELETE {{host}}/admin/category
Content-Type: application/json

{
    "idCategory": "6160158b0435705dbe1464c7"
}

###
DELETE {{host}}/admin/product
Content-Type: application/json

{
    "idProduct": "61601491e5599702fd7daf41"
}

###
PATCH {{host}}/admin/user
Content-Type: application/json

{
    "idUser": "6151a7b8ac39ee8974e0d43a",
    "update": {
    "email" : "A van teo",
    "firstName" : "asfasfasfasfsa",
    "lastName" : "sdgsdgsdgsdgsdgsd",
    "status" : "Active",
    "gender" : "Male",
    "phonenumber" : "1572727",
    "role" : "User",
    "wishlist" : [],
    "cart" : ["dfsdfsdfd"],
    "DOB": "Mon Oct 11 2021 13:44:00 GMT+0700 (Indochina Time)"
    }
}

###
DELETE {{host}}/admin/user
Content-Type: application/json

{
    "idUser": "6151a7b8ac39ee8974e0d43a"
}

###
DELETE {{host}}/admin/order
Content-Type: application/json

{
    "idOrder": "615e693b93c2b1eaa5f52149"
}

###
POST {{host}}/admin/discount
Content-Type: application/json

{
    "code": "TEST1",
    "expireDate": "Mon Oct 31 2021 13:44:00 GMT+0700 (Indochina Time)",
    "startDate": "Mon Oct 13 2021 13:44:00 GMT+0700 (Indochina Time)",
    "amount": 50

}

###
POST {{host}}/checkDiscount
Content-Type: application/json

{
    "code": "3131"
}

###
POST {{host}}/admin/user
Content-Type: application/json

{
    "email": "nhattan24121999@gmail.com",
    "password": "123456",
    "firstName": "Nhat",
    "lastName": "Tan",
    "gender": "Male",
    "DOB": "Tue Oct 12 2021 20:34:16 GMT+0700 (Indochina Time)",
    "phonenumber": "2348543241"
}

###
GET {{host}}/admin/discount

###
PATCH {{host}}/admin/discount  
Content-Type: application/json

{
    "code": "HELLOWORLD",
    "expireDate": "Tue Oct 12 2021 20:34:16 GMT+0700 (Indochina Time)",
    "amount": 60
}

###
POST {{host}}/admin/register
Content-Type: application/json

{
    "email": "tvnt221@gmail.com",
    "firstName": "Nhat",
    "lastName": "Tan",
    "role": "admin",
    "gender": "Male",
    "phonenumber": "45634536534"
}

###
POST {{host}}/addOrder
Content-Type: application/json

{
    "orderItems": [{
        "idProduct": "61124f8570dfe42c98e9925f",
        "name": "ssvsdvdsvd",
        "quantity": 1,
        "price": 10
    }, {
        "idProduct": "611ca8c435f54f9329280f50",
        "name": "sdifkjsdhkds",
        "quantity": 2,
        "price": 14
    }],
    "idUser": "615331ffc7dc43e2e5c84f45",
    "discount": "test1",
    "email": "nhattan24121999@gmail.com",
    "firstName": "123456",
    "lastName": "123456",
    "company": "gwegweg",
    "address": "Ho Chi Minh",
    "apartment": "wegwegew",
    "city": "Ho Chi Minh",
    "country": "Viet Nam",
    "postalCode": "123456",
    "phone": "123456",
    "number": 4242424242424242,
    "exp_month": 12,
    "exp_year": 2025,
    "cvc": 522
}

###
POST {{host}}/login
Content-Type: application/json

{
    "email": "tvnt221@gmail.com",
    "password": "700621"
}

###
GET {{host}}/wishlist
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNjk0NGVlZThkZThhOWQ2NjJiOGUwOCIsImlhdCI6MTYzNDI4ODkwOCwiZXhwIjoxNjM0Mzc1MzA4fQ.gbTC7ndB7ACZS4U9OHSNNfuPaH6iscWiZyo0hV7z1zg


###
GET {{host}}/admin/user

###
GET {{host}}/admin/revenue